export enum Limit {
    MinQuestionsNumber = 1,
    MinChoicesNumber = 2,
    MaxChoicesNumber = 4,
    MinGoodChoices = 1,
    MinBadChoices = 1,
    MinPoints = 10,
    MaxPoints = 100,
    MaxQuestionLength = 200,
    MaxChoiceLength = 100,
    MaxTitleLength = 100,
    MaxDescriptionLength = 500,
    MaxDuration = 60,
    MinDuration = 10,
    MaxNameLength = 20,
    QcmRequiredPanicCount = 10,
    QrlRequiredPanicCount = 20,
    MaxQcmAnswerLength = 100,
    MaxQrlAnswerLength = 200,
}
